apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeploy
  name: nodeser
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeploy
  type: NodePort
status:
  loadBalancer: {}
